ALTER TABLE suroit_courses
    ALTER COLUMN codestifligne DROP NOT NULL,
    ALTER COLUMN antenne DROP NOT NULL,
    ALTER COLUMN idtm DROP NOT NULL,
    ALTER COLUMN idmiss DROP NOT NULL,
    ALTER COLUMN course DROP NOT NULL,
    ALTER COLUMN nommiss DROP NOT NULL,
    ALTER COLUMN sens DROP NOT NULL,
    ALTER COLUMN numseq DROP NOT NULL,
    ALTER COLUMN hrpass DROP NOT NULL,
    ALTER COLUMN idptar DROP NOT NULL,
    ALTER COLUMN zdep DROP NOT NULL;
